# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  branches:
    include:
      - refs/heads/main
      - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GoTool@0
  inputs:
    version: '1.16'
  displayName: 'Install Go'

- script: go run mage.go ConfigureAgent
  displayName: "Configure Agent"

- script: mage Test
  displayName: 'Test'

- script: mage XBuildAll
  displayName: 'Cross Compile'

- script: mage Publish
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
  displayName: 'Publish'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
